variables:
    GIT_SUBMODULE_STRATEGY: none
    DOCKER_AUTH_CONFIG: '{ "auths": { "registry.gitlab.com": { "auth": "Z2l0bGFiK2RlcGxveS10b2tlbi0xMTI1OTA3OkdTQjRNaEVMVEFSVDlfY3d4eEFu" } } }'

stages:
    - build
    - test

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - target

default:
    tags:
        - picodata
    image: registry.gitlab.com/picodata/picodata/sbroad/sbroad-builder:0.2.0

build:
    stage: build
    script:
        - make
    artifacts:
      paths:
        - target/release/libsbroad.so
      expire_in: 1 week

lint:
    stage: test
    script:
        - make lint

test:
    before_script:
      - git clean -xfd
      - git submodule foreach --recursive git clean -xfd
      - git reset --hard
      - git submodule foreach --recursive git reset --hard
      - git submodule sync --recursive
      - git submodule update --init --recursive
    stage: test
    script:
        - make test_all
        - ls target/debug/
        - ls test_app/.rocks/lib/tarantool/
