stages:
    - build
    - test

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - target

default:
    tags:
        - picodata
    image: registry.gitlab.com/picodata/dockers/brod-builder:0.7

build:
    stage: build
    script:
        - make
    artifacts:
      paths:
        - target/release/libsbroad.so
      expire_in: 1 week

lint:
    stage: test
    script:
        - make lint

test:
    stage: test
    script:
        - make test_all
        - ls target/debug/
        - ls test_app/.rocks/lib/tarantool/
