variables:
  BASE_IMAGE_NAME: $CI_REGISTRY_IMAGE
  BASE_IMAGE_TAG: $CI_COMMIT_SHA
  DOCKER_AUTH_CONFIG: $DOCKER_AUTH_RO

workflow:
  # See https://docs.gitlab.com/ee/ci/jobs/job_control.html#avoid-duplicate-pipelines
  rules:
    # To avoid duplicate pipelines we disable merge request events,
    # leaving only pushes and manual triggering.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"

default:
  tags:
    - docker

stages:
  - build-base-image
  - lint
  - pack-doc
  - upload
  - deploy

build-base-image:
  stage: build-base-image
  variables:
    DOCKERFILE: "Dockerfile"
    PUSH_DOCKER: ""
    GIT_USERNAME: $CI_REGISTRY_USER
    GIT_PASSWORD: $CI_REGISTRY_PASSWORD
  image:
    name: docker-public.binary.picodata.io/kaniko-project/executor:v1.14.0-debug
    entrypoint: ['']
    pull_policy: [if-not-present]
  script:
    - echo "Build picodata doc..."
    - cd docker/static
    - >
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ${DOCKERFILE}
      --build-arg COMMIT_HASH=${CI_COMMIT_SHA} ${PUSH_DOCKER}
      --cache=false --cache-run-layers=true --single-snapshot --compressed-caching=false --use-new-run --snapshot-mode=redo --cleanup
      --destination ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}

lint:
  image: ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
  stage: lint
  script:
    - echo "Checking picodata doc..."
    - make lint
    - echo "Picodata doc successfully checked"

pack-doc:
  image: ${BASE_IMAGE_NAME}:${BASE_IMAGE_TAG}
  stage: pack-doc
  script:
    - echo "Pack picodata doc..."
    - VER=$(date +%Y%m%d%H%M%S)
    - FNAME="picodata-doc-${VER}-${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}.tgz"
    - echo "FNAME=$FNAME" | tee .vars
    - mkdocs build -d site --strict
    - pushd site
    - tar -cvzf ../$FNAME ./
    - popd
    - echo "Picodata doc successfully packed."
  artifacts:
    paths:
      - picodata-doc-*.tgz
    reports:
      dotenv: .vars

upload-doc-to-binary:
  image: docker.binary.picodata.io/curlimages/curl
  stage: upload
  script:
    - echo "Upload picodata doc to binary..."
    - echo "FNAME=$FNAME"
    - 'curl --fail -H "Authorization: Basic ${WWW_RAW_RW}" --upload-file $FNAME https://binary.picodata.io/repository/www-raw/$FNAME'
    - echo "Picodata doc successfully uploaded to binary."
  needs:
    - job: pack-doc
      artifacts: true

.deploy:
  stage: deploy
  variables:
    STAGE: TEST
    PICODATA_DOC: $FNAME
  trigger:
    project: 'picodata/web-site/infra'
    branch: 'main'
    strategy: depend
  needs:
    - job: pack-doc
      artifacts: true

deploy-doc-to-test-main:
  extends:
    - .deploy
  rules:
    - if: $CI_COMMIT_BRANCH ==  $CI_DEFAULT_BRANCH

deploy-doc-to-test-devbranch:
  extends:
    - .deploy
  rules:
    - if: $CI_COMMIT_BRANCH !=  $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: true
  variables:
    PICODATA_DOC_SUBDIR: 'branch-${CI_COMMIT_BRANCH}'

deploy-doc-to-prod:
  extends:
    - .deploy
  rules:
    - if: $CI_COMMIT_BRANCH ==  $CI_DEFAULT_BRANCH
  variables:
    STAGE: PROD
