variables:
    GIT_SUBMODULE_STRATEGY: none

stages:
    - build
    - test

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - target

default:
    tags:
        - picodata
    image: docker-public.binary.picodata.io/sbroad-builder:0.2.0

build:
    stage: build
    script:
        - make
    artifacts:
      paths:
        - target/release/libsbroad.so
      expire_in: 1 week

lint:
    stage: test
    script:
        - make lint

test:
    before_script:
      - git clean -xfd
      - git submodule foreach --recursive git clean -xfd
      - git reset --hard
      - git submodule foreach --recursive git reset --hard
      - git submodule sync --recursive
      - git submodule update --init --recursive
    stage: test
    script:
        - make test_all
        - ls target/debug/
        - ls test_app/.rocks/lib/tarantool/
