stages:
    - build
    - test

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - target

build:
    stage: build
    tags:
        - docker
    image: registry.gitlab.com/picodata/dockers/brod-builder:0.3

    script:
        - make
    artifacts:
      paths:
        - target/debug/libsbroad.so
      expire_in: 1 week

lint:
    stage: test
    tags:
        - docker
    image: registry.gitlab.com/picodata/dockers/brod-builder:0.3
    script:
        - make lint

test:
    stage: test
    tags:
        - docker
    image: registry.gitlab.com/picodata/dockers/brod-builder:0.3
    script:
        - make test_all
        - ls target/debug/
        - ls test_app/.rocks/lib/tarantool/
