variables:
    GIT_SUBMODULE_STRATEGY: none

stages:
    - build
    - test

cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - target

default:
    tags:
        - picodata
    image: docker-public.binary.picodata.io/picodata/picodata/sbroad/sbroad-builder:0.4.1
build:
    before_script:
      - make init
    stage: build
    script:
        - make
    artifacts:
      paths:
        - target/release/libsbroad.so
      expire_in: 1 week

lint:
    stage: test
    script:
        - make lint

unit:
    before_script:
      - make init
    stage: test
    script:
        - make test

integration:
    before_script:
      - make init
    stage: test
    script:
        - make test_integration

bench:
    before_script:
      - make init 
    stage: test
    script:
        - make bench_check
