[package]
name = "picodata"
version = "0.1.0"
edition = "2018"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1"
clap = "^2.33"
errno = "0.2.8"
inventory = "0.2.0"
libc = "0.2.108"
raft = "0.6.0"
serde = "1.0"
serde_json = "1.0"
structopt = "^0.3"
rmp-serde = "1.0"
tempfile = "3"
thiserror = "1.0"
indoc = "1.0"
nix = "0.23.1"

[dependencies.slog]
version = "2.7.0"
features = ["max_level_trace", "release_max_level_trace"]

[dependencies.tarantool]
path = "./tarantool/tarantool"
version = "0.6"
features = ["schema"]

[dev-dependencies]
assert_cmd = "2.0"
predicates = "2.0"
tempfile = "3"

[build-dependencies]
cmake = "^0"

[[bin]]
name = "picodata"
doctest = false

[[test]]
name = "cli"
path = "test/cli.rs"
harness = true

[[test]]
name = "inner"
path = "test/inner.rs"
harness = false
