[package]
name = "picodata"
version = "22.11.0"
edition = "2021"
autotests = false
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1"
clap = {version = "3", features = ["derive", "env"]}
errno = "0.2.8"
libc = "0.2.108"
raft = "0.6.0"
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11"
rmp-serde = "1.0"
tempfile = "3"
thiserror = "1.0"
nix = "0.23.1"
uuid = {version = "1.0", features = ["v3"]}
futures = "0.3.25"

[dependencies.protobuf]
version = "2.27"
features = ["bytes"]

[dependencies.slog]
version = "2.7.0"
features = ["max_level_trace", "release_max_level_trace"]

[dependencies.tarantool]
path = "./tarantool/tarantool"
version = "0.7"
features = ["picodata", "test"]

[dev-dependencies]
rand = "0.8.5"
pretty_assertions = "0.6.1"

[features]
load_test = []
webui = []

[lib]
doctest = true

[[test]]
name = "inner"
path = "test/inner.rs"
harness = false
