[package]
name = "sbroad"
version = "0.1.0"
authors = ["Igor Kuznetsov <kuznetsovin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decimal = "2.1.0"
fasthash = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
sqlparser = "0.11.0"
tarantool = "0.4.2"
traversal = "0.1.2"
yaml-rust = "0.4.1"

[dev-dependencies]
pretty_assertions = "1.0.0"

[lib]
crate-type = ["cdylib"]
