[package]
name = "picodata"
version = "0.1.0"
edition = "2018"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = []

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
errno = "0.2.8"
libc = "0.2.108"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3"

[lib]
name = "picolib"
path = "picolib/lib.rs"
crate-type = ["rlib", "cdylib"]
doctest = false
test = false

[[bin]]
name = "picodata"
path = "picodata/main.rs"
test = false

[[test]]
name = "cli"
harness = true
