[package]
name = "picodata"
version = "0.1.0"
edition = "2018"
autotests = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = []

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
errno = "0.2.8"
inventory = "0.2.0"
libc = "0.2.108"

[dependencies.slog]
version = "2.7.0"
features = ["max_level_trace", "release_max_level_trace"]

[dependencies.tarantool]
path = "../tarantool-module/tarantool"
version = "0.4.2"

[dev-dependencies]
assert_cmd = "2.0"
tempfile = "3"

[lib]
name = "picolib"
path = "picolib/lib.rs"
crate-type = ["rlib", "cdylib"]
doctest = false
test = false

[[bin]]
name = "picodata"
path = "picodata/main.rs"
test = true
harness = true
doctest = false

[[test]]
name = "cli"
harness = true
