[package]
name = "picodata"
version = "23.6.0"
edition = "2021"
autotests = false
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1"
clap = {version = "3", features = ["derive", "env"]}
errno = "0.2.8"
indoc = "2"
libc = "0.2.108"
raft = "0.6.0"
serde = "1.0"
serde_json = "1.0"
serde_bytes = "0.11"
rmp-serde = "1.0"
tempfile = "3"
thiserror = "1.0"
nix = "0.23.1"
uuid = {version = "1.0", features = ["v3"]}
futures = "0.3.25"
once_cell = "1.17.1"
blake3 = "=1.3.3"

[dependencies.protobuf]
version = "2.27"
features = ["bytes"]

[dependencies.sbroad-core]
version = "0.1"
path = "sbroad/sbroad-core"

[dependencies.slog]
version = "2.7.0"
features = ["max_level_trace", "release_max_level_trace"]

[dependencies.tarantool]
path = "./tarantool/tarantool"
version = "1.2.0"
features = ["picodata", "test"]

[dev-dependencies]
rand = "0.8.5"
pretty_assertions = "0.6.1"

[build-dependencies]
nix = "0.23.1"

[patch."https://git.picodata.io/picodata/picodata/tarantool-module.git"]
tarantool = { path = "./tarantool/tarantool" }

[features]
load_test = []
webui = []

[lib]
doctest = true

[[test]]
name = "inner"
path = "test/inner.rs"
harness = false
