[package]
name = "sbroad"
version = "0.1.0"
authors = ["Igor Kuznetsov <kuznetsovin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
decimal = "2.1.0"
fasthash = "0.4.0"
pest = "2.0"
pest_derive = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
sqlparser = "0.11.0"
tarantool = { git = "https://sbroad-cargo-token:t-nZyqJVVuhGQv17BX6v@gitlab.com/picodata/picodata/tarantool-module.git", rev="6f6bc329"}
traversal = "0.1.2"
yaml-rust = "0.4.1"

[dev-dependencies]
pretty_assertions = "1.0.0"
rmp-serde = "0.14"

[lib]
crate-type = ["cdylib"]
