site_name: Портал документации Picodata
site_description: Picodata documentation site
repo_url: https://git.picodata.io/picodata/picodata/docs


nav:
  - Ознакомление с ПО Picodata:
    - Общее описание продукта: description.md
    - Преимущества Picodata: benefits.md
    - Преимущества языка Rust при разработке приложений: benefits_rust.md
    - Работа с SQL в Picodata: sbroad/sql_index.md
  - Инструкции и руководства:
    - Установка Picodata: install.md
    - Развертывание кластера: deploy.md
    - Мониторинг кластера: monitoring.md
    - Пример работы с кластером Picodata: tutorial.md
    - Пример работы с приложением Picodata SQL: sbroad/sql_tutorial
  - Справочные материалы:
    - Аргументы командной строки Picodata: cli.md
    - Публичный API Picodata: api.md
    - Команды SQL: sbroad/sql_queries
    - Поддерживаемые типы данных: sbroad/sql_datatypes
    - Поддерживаемые функции стандарта SQL: sbroad/sql_reference.md
    - Глоссарий: glossary.md
  - Архитектурная документация:
    - Схема инициализации кластера: clustering.md
    - Принципы работы распределенного SQL: sbroad/sql_review
  

theme:
    name: material
    custom_dir: overrides
    font:
        text: Inter
    logo: assets/logo-full.svg
    logo_mobile: assets/logo.svg
    favicon: assets/favicon.png
    locale: ru
    language: ru
    features:
        - navigation.indexes
        - navigation.path
        - navigation.sections
        - toc.follow
        - content.code.copy
        
 

extra:
    homepage: https://docs.picodata.io/
    analytics:
     provider: google
     property: G-6X8Z5N2CGR
     feedback:
      title: Была ли эта информация полезной для вас?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Да, это было полезно
          data: 1
          note: >-
            Благодарим за отзыв!
        - icon: material/emoticon-sad-outline
          name: Страница требует улучшения
          data: 0
          note: >- 
            Благодарим за отзыв! <a href="https://t.me/picodataru" target="_blank" rel="noopener">Напишите</a>, что бы вы хотели улучшить на этой странице или в целом на сайте документации.
       
extra_css:
    - extra/style.css

plugins:
    - inline-svg
    - git-revision-date-localized:
        enable_creation_date: true
    - search:
        lang: 
          - en
          - ru
markdown_extensions:
  - attr_list
  - md_in_html
  - meta
  - toc:
        permalink: True
  
