# Конфигурация MkDocs
# https://www.mkdocs.org/user-guide/configuration/

# Общие настройки
# site_name — https://www.mkdocs.org/user-guide/configuration/#site_name
# site_description — https://www.mkdocs.org/user-guide/configuration/#site_description
# repo_url — https://www.mkdocs.org/user-guide/configuration/#repo_url
# edit_uri — https://www.mkdocs.org/user-guide/configuration/#edit_uri
site_name: Портал документации Picodata
site_description: Picodata documentation site
repo_url: https://git.picodata.io/picodata/picodata/docs
edit_uri: -/blob/main/docs/

# Исключения из навигации
# https://www.mkdocs.org/user-guide/configuration/#not_in_nav
not_in_nav: |
  /index.md

# Навигация
# https://www.mkdocs.org/user-guide/configuration/#nav
nav:
  - Ознакомление с ПО Picodata:
    - overview/description.md
    - overview/benefits.md
    - overview/glossary.md
    - overview/feedback.md
  - Инструкции и руководства:
    - tutorial/install.md
    - tutorial/deploy.md
    - tutorial/connecting.md
    - tutorial/sql_examples.md
    - tutorial/webui.md
    - tutorial/access_control.md
    - tutorial/ldap.md
    - tutorial/monitoring.md
    - tutorial/audit_log.md
  - Справочные материалы:
    - reference/cli.md
    - reference/sql_types.md
    - reference/sql_queries.md
    - reference/api.md
    - reference/ansi_sql.md
    - reference/audit_events.md
  - Архитектура:
    - architecture/distributed_sql.md
    - architecture/discovery.md
    - architecture/instance_lifecycle.md
    - architecture/topology_management.md
    - architecture/raft_failover.md
    - architecture/system_tables.md
    # - architecture/proc_api.md

  - Обеспечение безопасности:
    - security/os.md
    - security/runtime.md
    - security/audit_log.md
    - security/integrity.md

# Настройки темы Material
  ## name, custom_dir — https://squidfunk.github.io/mkdocs-material/customization/#setup-and-theme-structure
  ## font — https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#regular-font
  ## logo — https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo
  ## favicon — https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#favicon
  ## language — https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#site-language
  ## features:
    ### toc.follow — https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#anchor-following
    ### content.code.copy — https://squidfunk.github.io/mkdocs-material/upgrade/#contentcodecopy
    ### content.action.edit — https://squidfunk.github.io/mkdocs-material/upgrade/#contentaction
theme:
  name: material
  custom_dir: overrides
  font:
    text: Inter
  logo: assets/logo-full.svg
  logo_mobile: assets/logo.svg
  favicon: assets/favicon.png
  language: ru
  features:
    - toc.follow
    - content.code.copy
    - content.action.edit

# Дополнительные настройки темы Material
  ## homepage — https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo
  ## analytics — https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-analytics/#setting-up-site-analytics
extra:
  analytics:
    provider: google
    property: G-6X8Z5N2CGR
    feedback:
      title: Была ли эта информация полезной для вас?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Да, это было полезно
          data: 1
          note: >-
            Благодарим за отзыв!
        - icon: material/emoticon-sad-outline
          name: Страница требует улучшения
          data: 0
          note: >-
            Благодарим за отзыв! <a href="https://t.me/picodataru"
            target="_blank" rel="noopener">Напишите</a>, что бы вы хотели
            улучшить на этой странице или в целом на сайте документации.

# Кастомизация CSS
# https://www.mkdocs.org/user-guide/configuration/#extra_css
extra_css:
  - extra/style.css

# Плагины MkDocs
# https://www.mkdocs.org/user-guide/configuration/#plugins
  ## > inline-svg
  ## Вставляет изображений формата svg с относительными ссылками
  ## https://pypi.org/project/mkdocs-plugin-inline-svg/
  ## > search
  ## Добавляет в хедер панель поиска
  ## https://www.mkdocs.org/user-guide/configuration/#search
  ## https://squidfunk.github.io/mkdocs-material/plugins/search/
plugins:
  - inline-svg
  - search:
      lang:
        - en
        - ru

# Расширения Python Markdown
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
  ## > attr_list
  ## Добавляет синтаксис для определения атрибутов различных элементов HTML в выводе Markdown.
  ## Используется для кастомизации якорей в формате {: #anchor }. Двоеточие и пробелы можно убирать
  ## https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/#attribute-lists
  ## https://python-markdown.github.io/extensions/attr_list/
markdown_extensions:
  - attr_list

# Валидация ссылок
# https://www.mkdocs.org/user-guide/configuration/#validation
validation:
  links:
    unrecognized_links: warn

# https://www.mkdocs.org/user-guide/configuration/#hooks
hooks:
  - ./hooks/filter_logs.py
  - ./hooks/check_headers.py
  - ./hooks/check_links.py
