site_name: Портал документации Picodata

hide:
  - navigation
  - toc
  
nav:
    - Главная: index.md
    - Описание продукта: description.md
    - Преимущества Picodata: benefits.md
    - Архитектура Picodata: arch.md
    - Преимуществая языка Rust: benefits_rust.md
    - Установка и первые шаги: install.md
    - Услуги: services.md
theme:
    name: material
    custom_dir: overrides
    font:
        text: Inter
    logo: assets/logo-full.svg
    logo_mobile: assets/logo.svg
    favicon: assets/favicon.png
    language: ru
    features:
        - tabs.navigation

extra:
    homepage: https://picodata.io/

extra_css:
    - extra/style.css

plugins:
    - search:
        lang: 
          - en
          - ru
markdown_extensions:
  - attr_list
  - md_in_html
  - meta
