site_name: Портал документации Picodata
site_description: Picodata documentation site

nav:
    - Главная: index.md
    - Общее описание продукта: description.md
    - Преимущества Picodata: benefits.md
    - Преимущества языка Rust: benefits_rust.md
    - Установка и первые шаги: install.md
    - Описание параметров запуска: cli.md
    - Инструкция по развертыванию: deploy.md

theme:
    name: material
    custom_dir: overrides
    font:
        text: Inter
    logo: assets/logo-full.svg
    logo_mobile: assets/logo.svg
    favicon: assets/favicon.png
    locale: ru
    language: ru
    features:
        - tabs.navigation
        - navigation.tracking
        - navigation.sections

extra:
    homepage: https://docs.picodata.io/
    analytics:
     provider: google
     property: G-6X8Z5N2CGR

extra_css:
    - extra/style.css

plugins:
    - search:
        lang: 
          - en
          - ru
markdown_extensions:
  - attr_list
  - md_in_html
  - meta
  - toc:
        permalink: True
  
