# MkDocs configuration reference:
# https://www.mkdocs.org/user-guide/configuration/

site_name: Портал документации Picodata
site_description: Picodata documentation site
repo_url: https://git.picodata.io/picodata/picodata/docs
edit_uri: -/blob/main/docs/

nav:
  - Ознакомление с ПО Picodata:
    - overview/description.md
    - overview/benefits.md
    - overview/glossary.md
    - overview/feedback.md
  - Инструкции и руководства:
    - tutorial/install.md
    - tutorial/deploy.md
    - tutorial/monitoring.md
    - tutorial/connecting.md
    - tutorial/webui.md
    - tutorial/ldap.md
    - tutorial/access_control.md
    - tutorial/sql_examples.md
    - tutorial/audit_log.md
  - Справочные материалы:
    - reference/cli.md
    - reference/sql_types.md
    - reference/sql_queries.md
    - reference/api.md
    - reference/ansi_sql.md
    - reference/audit_events.md
  - Архитектура:
    - architecture/distributed_sql.md
    - architecture/discovery.md
    - architecture/instance_lifecycle.md
    - architecture/topology_management.md
    - architecture/raft_failover.md
    - architecture/system_tables.md

theme:
  name: material
  custom_dir: overrides
  font:
    text: Inter
  logo: assets/logo-full.svg
  logo_mobile: assets/logo.svg
  favicon: assets/favicon.png
  language: ru
  features:
    - navigation.indexes
    - navigation.path
    - toc.follow
    - content.code.copy
    - content.action.edit

extra:
  homepage: https://docs.picodata.io/
  analytics:
    provider: google
    property: G-6X8Z5N2CGR
    feedback:
      title: Была ли эта информация полезной для вас?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Да, это было полезно
          data: 1
          note: >-
            Благодарим за отзыв!
        - icon: material/emoticon-sad-outline
          name: Страница требует улучшения
          data: 0
          note: >-
            Благодарим за отзыв! <a href="https://t.me/picodataru"
            target="_blank" rel="noopener">Напишите</a>, что бы вы хотели
            улучшить на этой странице или в целом на сайте документации.

extra_css:
  - extra/style.css

plugins:
  # https://pypi.org/project/mkdocs-plugin-inline-svg/
  - inline-svg

  # https://squidfunk.github.io/mkdocs-material/plugins/search/
  - search:
      lang:
        - en
        - ru

markdown_extensions:
  - attr_list
  - md_in_html
  - meta
  - toc:
      permalink: False
