site_name: Портал документации Picodata
site_description: Picodata documentation site
repo_url: https://git.picodata.io/picodata/picodata/docs


nav:
  - Ознакомление с ПО Picodata:
    - description.md
    - benefits.md
    - glossary.md
    - feedback.md
  - Инструкции и руководства:
    - install.md
    - deploy_on_hosts.md
    - monitoring.md
    - tutorial_first_steps.md
    - auth_ldap.md
    - tutorial_data.md
  - Справочные материалы:
    - cli.md
    - sql/datatypes.md
    - sql/queries.md
    - api.md
    - sql/reference.md
  - Архитектура:
    - sql/broadcasted_sql.md
    - discovery.md
    - raft_voters.md
    - clustering.md
theme:
    name: material
    custom_dir: overrides
    font:
        text: Inter
    logo: assets/logo-full.svg
    logo_mobile: assets/logo.svg
    favicon: assets/favicon.png
    language: ru
    features:
        - navigation.indexes
        - navigation.path
        - toc.follow
        - content.code.copy



extra:
    homepage: https://picodata.io/
    analytics:
     provider: google
     property: G-6X8Z5N2CGR
     feedback:
      title: Была ли эта информация полезной для вас?
      ratings:
        - icon: material/emoticon-happy-outline
          name: Да, это было полезно
          data: 1
          note: >-
            Благодарим за отзыв!
        - icon: material/emoticon-sad-outline
          name: Страница требует улучшения
          data: 0
          note: >-
            Благодарим за отзыв! <a href="https://t.me/picodataru" target="_blank" rel="noopener">Напишите</a>, что бы вы хотели улучшить на этой странице или в целом на сайте документации.

extra_css:
    - extra/style.css

plugins:
    - inline-svg
    - git-revision-date-localized:
        enable_creation_date: true
    - search:
        lang:
          - en
          - ru
markdown_extensions:
  - attr_list
  - md_in_html
  - meta
  - toc:
        permalink: False
