site_name: Портал документации Picodata
site_description: Picodata documentation site

nav:
  - Главная страница: index.md
  - Ознакомление с ПО Picodata:
    - Общее описание продукта: description.md
    - Преимущества использования Picodata: benefits.md
    - Преимущества языка Rust при разработке приложений: benefits_rust.md
    - Общая схема инициализации кластера: clustering.md
    - Работа с SQL в Picodata: sbroad/sql_index.md
  - Инструкции и руководства:
    - Установка Picodata: install.md
    - Инструкция по развертыванию: deploy.md
    - Пример работы с кластером Picodata: tutorial.md
  - Справочные материалы:
    - Описание параметров запуска Picodata: cli.md
    - Глоссарий основных терминов и определений: glossary.md
    - Поддерживаемые функции стандарта SQL: sbroad/sql_reference.md


theme:
    name: material
    custom_dir: overrides
    font:
        text: Inter
    logo: assets/logo-full.svg
    logo_mobile: assets/logo.svg
    favicon: assets/favicon.png
    locale: ru
    language: ru
    features:
        - navigation.indexes
        - navigation.path
        - navigation.sections
        - content.code.copy
 

extra:
    homepage: https://docs.picodata.io/
    analytics:
     provider: google
     property: G-6X8Z5N2CGR

extra_css:
    - extra/style.css

plugins:
    - search:
        lang: 
          - en
          - ru
markdown_extensions:
  - attr_list
  - md_in_html
  - meta
  - toc:
        permalink: True
  
