site_name: Портал документации Picodata
nav:
    - Главная: index.md
    - Преимущества: benefits.md
    - Описание услуг: services.md
    - Установка и первые шаги: install.md
theme: readthedocs
plugins:
    - search:
        lang: 
          - en
          - ru
