[package]
name = "plugin-example2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
picodata-sdk = {path = "../picodata-sdk"}
serde_json = "1.0.104"

[lib]
crate-type = ["lib", "cdylib"]
